server:
  port: 8081

spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER:configuser}:${CONFIG_SERVER_PASSWORD:configpass}@localhost:8888

jwt:
  secret: ${JWT_SECRET:default-very-long-secret-key-at-least-256-bits-long-for-hmac-sha256}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka